name: Continuous Integration

# this is trigger CI on push and PR for main branch only
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# this is trigger CI on all kinds of branches and PRs
on:
  push:
  pull_request:
    branches: [main,dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Obtiene todo el historial para todas las ramas y tags
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format

      - name: Run tests with vitest
        run: npm run test
